// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthOSgNqFCL_7ujBXz1bXyWltXMP7ZzyE',
    appId: '1:351739997316:web:1a1b12ab71a572cffae6d1',
    messagingSenderId: '351739997316',
    projectId: 'myhealthdiary-4e537',
    authDomain: 'myhealthdiary-4e537.firebaseapp.com',
    storageBucket: 'myhealthdiary-4e537.firebasestorage.app',
    measurementId: 'G-VYQN9QLT7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-psSjTts6FVxcz19LQpMp9hOD6kSXhbw',
    appId: '1:351739997316:android:91b8d473d9b0c097fae6d1',
    messagingSenderId: '351739997316',
    projectId: 'myhealthdiary-4e537',
    storageBucket: 'myhealthdiary-4e537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5IQ2ab3khOtGBRMLkLU0hB9AFQZFhvM4',
    appId: '1:351739997316:ios:33611caa48da22a1fae6d1',
    messagingSenderId: '351739997316',
    projectId: 'myhealthdiary-4e537',
    storageBucket: 'myhealthdiary-4e537.firebasestorage.app',
    iosBundleId: 'com.example.myhealthdiaryApp',
  );
}
